### ISSUE TITLE
TypeError: c.resize is not a function

### ISSUE THREAD

**Issue by Chaotnix** [KoltesDigital/shadertoy-exporter#21]
I tried running the shadertoy-exporter-1.4.0.exe on Windows 10, Java 1.8. 
I get the error 'TypeError: c.resize is not a function'  as soon as i click on export.

**Comment by FullstackJack** [comment]
There is no Java here, it's built with Electron which is JavaScript.

**Comment by tdhooper** [comment]
This is probably because shadertoy removed their internal resize function, I had the same issue with my frame exporter plugin, here's how I fixed it there if anyone needs a reference implementation:

https://github.com/tdhooper/shadertoy-frame-exporter/commit/5f73b10e019d33ded11f94b6ff9a6882a27a2f2d

**Comment by Chaotnix** [comment]
Thanks for the clarification. 
Unfortunately I am not able to fix it by myself, because I can't even compile the code in VS Code.
There are always unresolved dependancies. 
Maybe be I will try again, when I have some better understanding how npm, jspm an the other tools work.
Till then I will use tdhooper/shadertoy-frame-exporter. It does a great job.

**Comment by KoltesDigital** [comment]
Sorry for being late. I've fixed the resizing part. https://github.com/KoltesDigital/shadertoy-exporter/commit/9d471c358684c357bd2b0fb57420672113f3b04c @tdhooper I tried to use your change, but after all I copied the code executed on going fullscreen, this has the advantage of not visually resizing the canvas!

However, indeed the build process is now broken. I'll have a look at it.

**Comment by benoitmar** [comment]
Hello all,
I downloaded yesterday the shadertoy-exporter-1.4.0.exe.
I still get the c.resize error. Do you plan to make a new build with the fix ?

Thank you for making this tool, shadertoys rocks !

**Comment by Hitthesurf** [comment]
> Hello all, I downloaded yesterday the shadertoy-exporter-1.4.0.exe. I still get the c.resize error. Do you plan to make a new build with the fix ?
> 
> Thank you for making this tool, shadertoys rocks !

I got this today, for windows 10, and I get the c.resize error.

**Comment by JapanYoshi** [comment]
I am having the same exact issue!

**Comment by kilik128** [comment]
same here if somethink's have make new build it's can be good

**Comment by vladimirmujagic** [comment]
Any update regarding this issue? It's currently unusable

**Comment by sdedovic** [comment]
I was able to build and use on MacOS 12 (Monterey) after blowing away the `package-lock.json` file and upgrading `electron-builder` to `"^21.2.0"`.

**Comment by vladimirmujagic** [comment]
Thank you very much, it solved the issues. I was using released windows executable, works both on Linux and Windows when "building from source".

**Comment by KoltesDigital** [comment]
Sorry for being late again...

I finally took time to fix the CICD. As mentioned, the code was fixed months ago, but the CICD didn't actually published anything.

A working version is now available! https://github.com/KoltesDigital/shadertoy-exporter/releases/tag/1.5.4

But, well, this project is so old. Libraries are outdated, UI isn't friendly. If someone has time to take it over...
